# Generated by Django 4.1.7 on 2023-04-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Records'},
        ),
        migrations.RenameField(
            model_name='record',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='address',
            new_name='opportunity_id',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='city',
            new_name='sales_agent',
        ),
        migrations.RemoveField(
            model_name='record',
            name='email',
        ),
        migrations.RemoveField(
            model_name='record',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='record',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='record',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='record',
            name='state',
        ),
        migrations.RemoveField(
            model_name='record',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='record',
            name='account',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='close_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='record',
            name='close_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='deal_stage',
            field=models.CharField(blank=True, choices=[('Won', 'Won'), ('Lost', 'Lost'), ('In_progress', 'In_progress')], default='In_progress', help_text='Deal stage', max_length=15),
        ),
    ]
