# Generated by Django 4.1.7 on 2023-04-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_record_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Records'},
        ),
        migrations.RenameField(
            model_name='record',
            old_name='opportunity_id',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='account',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='record',
            name='close_date',
        ),
        migrations.RemoveField(
            model_name='record',
            name='close_value',
        ),
        migrations.RemoveField(
            model_name='record',
            name='deal_stage',
        ),
        migrations.RemoveField(
            model_name='record',
            name='sales_agent',
        ),
        migrations.AddField(
            model_name='record',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='zipcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
